/* tools/bake-chrome.mjs · starchitect.us v10
   ─────────────────────────────────────────────────────────────────────────────
   Why this exists.

   Every canonical page on starchitect.us opts into shared chrome with
   <body data-chrome="on" data-route="…">, and `home-fx.js` then BUILDS that
   chrome at runtime: the classification banner, the whole navigation, the
   telemetry bar and the entire footer. None of it is in the served HTML.

   Measured with JavaScript disabled, before this script ran:

     home.html       3 internal links · no nav · no footer · no entity line
     platform.html   2 internal links · no nav · no footer · NO ITAR NOTICE
     a-platform.html 12 links · nav · footer · ITAR · entity   ← the ORPHANED
                                                                 legacy page

   The orphaned older generation is better built for a crawler than the
   canonical site. Nine pages ship with no navigation a non-JS client can see,
   six of them with no ITAR notice in the document at all — which for a defense
   contractor is the one line you would want in the markup rather than assembled
   afterwards.

   This script generates that chrome statically and injects it, so the HTML
   carries its own navigation, footer, entity line and ITAR notice. It is
   deterministic and re-runnable: it strips any chrome it previously inserted
   before inserting again, so it can be run as often as you like.

   `home-fx.js` keeps every live behaviour — the UTC clock, the latency and
   track counters, scroll state, the correlator — because those bind by
   attribute (`[data-utc]`, `[data-latency]`, `[data-tracked]`) and bind to
   static markup exactly as well as to generated markup. Only `initChrome` is
   made to stand down, and only when it finds the chrome already present.

   Run:  node tools/bake-chrome.mjs [--check]
         --check exits non-zero if any page would change (for CI).
*/
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SITE = join(here, '..', 'starchitect-website');
const CHECK = process.argv.includes('--check');

/* The single source of truth for the IA. Mirrored from home-fx.js initChrome,
   which is where it lived when only the browser could see it. */
const NAV = [
  ['platform.html',     'Platform',     'platform'],
  ['capabilities.html', 'Capabilities', 'capabilities'],
  ['use-cases.html',    'Use Cases',    'use-cases'],
  ['resilience.html',   'Resilience',   'resilience'],
  ['security.html',     'Security',     'security'],
  ['acquisition.html',  'Acquisition',  'acquisition'],
  ['company.html',      'Company',      'company'],
];

const CLASSIFICATION = 'UNCLASSIFIED // DUAL-USE // ITAR 22 C.F.R. 120.10';
const ITAR = 'This site contains technical data as defined under the International Traffic in Arms ' +
             'Regulations (ITAR) (22 C.F.R. 120.10) and may not be exported or disclosed to any ' +
             'foreign person without prior U.S. Government authorization.';
const WM = 'assets/wordmark.png';

const BEGIN = '<!-- @chrome:begin  generated by tools/bake-chrome.mjs — do not hand-edit -->';
const END   = '<!-- @chrome:end -->';
const HBEGIN = '<!-- @chrome-head:begin  generated — do not hand-edit -->';
const HEND   = '<!-- @chrome-head:end -->';

/* Every page carries its own inline <style> in the head, AFTER all four
   stylesheet links. That block wins the cascade over site-v10.css no matter
   where the link sits, which is why the focus ring declared there never
   reached a focused .nav-logo: the computed outline came back
   `currentColor solid 0px`. Rather than fight it with !important in a file that
   still loses, the focus ring is emitted here, last in the head, where nothing
   in the page can outrank it. Everything else stays in site-v10.css. */
const HEAD_CSS = `${HBEGIN}
<style>
.skip.skip-to-main{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;
  clip:rect(0 0 0 0);clip-path:inset(50%);white-space:nowrap;border:0}
.skip.skip-to-main:focus{position:fixed;left:8px;top:8px;width:auto;height:auto;margin:0;overflow:visible;
  clip:auto;clip-path:none;z-index:200;background:#D4A03B;color:#060B17;padding:12px 18px;
  font-family:'Rajdhani',sans-serif;font-weight:700;letter-spacing:.04em;
  outline:2px solid #EFE9DD;outline-offset:2px}
.nav-logo:focus,.nav-links > a:focus,.nav-toggle:focus,.footer a:focus,.btn:focus,
.nav-logo:focus-visible,.nav-links > a:focus-visible,.nav-toggle:focus-visible,
.footer a:focus-visible,.btn:focus-visible{outline:2px solid #D4A03B;outline-offset:3px;border-radius:2px}
</style>
${HEND}`;

function head(route) {
  const links = NAV.map(([href, label, key]) =>
    `<a href="${href}"${key === route ? ' class="active"' : ''}>${label}</a>`).join('');
  return `${BEGIN}
<a class="skip skip-to-main" href="#main">Skip to content</a>
<div class="classification">${CLASSIFICATION}</div>
<nav class="nav" id="nav">
  <div class="nav-inner">
    <a class="nav-logo" href="home.html"><img src="${WM}" alt="STARCHITECT" width="150" height="20">
      <span class="pill"><b>A HYPATIUS</b>PLATFORM</span></a>
    <div class="nav-links" id="navLinks">${links}<a href="resources.html"${
      route === 'resources' ? ' class="active"' : ''}>Resources</a>
      <a href="home.html#briefing" class="btn btn-primary">Request briefing</a></div>
    <button class="nav-toggle" aria-label="Menu" aria-expanded="false" aria-controls="navLinks">&#9776;</button>
  </div>
</nav>
<div class="telebar" aria-hidden="true">
  <div class="telebar-inner">
    <span class="tb"><span class="live"></span><b>MESH NOMINAL</b> &middot; 5-TIER PACE</span>
    <span class="tb-sep"></span>
    <span class="tb">CORRELATOR <span class="g" data-latency>&lt; 500 ms</span></span>
    <span class="tb-sep"></span>
    <span class="tb">TRACKED <span class="c" data-tracked>4,471</span> &middot; GEO/CISLUNAR</span>
    <span class="tb-sep"></span>
    <span class="tb">BACKBONE <b>100% FOSS</b></span>
    <span class="tb-sep"></span>
    <span class="tb"><span data-utc>00:00:00 UTC</span></span>
  </div>
</div>
<span id="main" tabindex="-1"></span>
${END}`;
}

/* The footer carries the entity name, the credential stamp and the ITAR notice.
   Those three are the reason this bake matters most: they are legal and
   identity statements, and until now they existed only after JavaScript ran. */
function foot() {
  return `${BEGIN}
<footer class="footer">
  <div class="footer-grid">
    <div class="footer-brand"><img src="${WM}" alt="STARCHITECT" width="150" height="20">
      <p>The operating system for space warfare and BMC3I.</p>
      <div class="contact"><a href="mailto:leadership@hypati.us">leadership@hypati.us</a><br>
        <a href="tel:2532304166">253.230.4166</a><br>Charleston, SC</div></div>
    <div class="footer-col"><h4>Platform</h4><a href="platform.html">Operator console</a><a href="capabilities.html">Capabilities</a><a href="use-cases.html">Use cases</a><a href="resilience.html">PACE resilience</a></div>
    <div class="footer-col"><h4>Engage</h4><a href="security.html">Security</a><a href="acquisition.html">Acquisition</a><a href="resources.html">Resources</a></div>
    <div class="footer-col"><h4>Company</h4><a href="company.html">About</a><a href="company.html#leadership">Leadership</a><a href="press-kit.html">Press kit</a><a href="resources.html">Glossary</a><a href="https://hypati.us" target="_blank" rel="noopener">hypati.us &#8599;</a></div>
  </div>
  <div class="footer-bottom"><div>&copy; 2026 HYPATIUS, LLC &middot; STARCHITECT is a HYPATIUS platform.</div><div>UEI UKELB3UV76V6 &middot; CAGE 19S89</div></div>
  <div class="itar">${ITAR}</div>
</footer>
${END}`;
}

/* Remove any block this script inserted before, so re-runs are idempotent
   rather than cumulative. */
function strip(html) {
  const re = new RegExp(
    BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' +
    END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\n?', 'g');
  return html.replace(re, '');
}

let changed = [], skipped = [];
for (const file of readdirSync(SITE).filter(f => f.endsWith('.html')).sort()) {
  const path = join(SITE, file);
  const orig = readFileSync(path, 'utf8');
  const m = orig.match(/<body([^>]*)>/i);
  if (!m || !/data-chrome=["'](?:on|baked)["']/.test(m[1])) { skipped.push(file); continue; }
  const route = (m[1].match(/data-route=["']([^"']+)["']/) || [, ''])[1];

  let html = strip(orig);
  html = html.replace(new RegExp(
    HBEGIN.replace(/[.*+?^${}()|[\]\\]/g,'\\$&') + '[\\s\\S]*?' +
    HEND.replace(/[.*+?^${}()|[\]\\]/g,'\\$&') + '\\n?', 'g'), '');
  html = html.replace(/<\/head>/i, `${HEAD_CSS}\n</head>`);
  // data-chrome flips to "baked" so home-fx.js knows to stand down. Keeping the
  // attribute (rather than deleting it) means the page still declares that it
  // HAS chrome, which is what the harness checks for.
  html = html.replace(/<body([^>]*)>/i, (all, attrs) =>
    `<body${attrs.replace(/data-chrome=["'](?:on|baked)["']/, 'data-chrome="baked"')}>`);
  html = html.replace(/(<body[^>]*>)/i, `$1\n${head(route)}`);
  html = html.replace(/<\/body>/i, `${foot()}\n</body>`);

  if (html !== orig) { changed.push(file); if (!CHECK) writeFileSync(path, html); }
}

console.log(`baked ${changed.length} page(s): ${changed.join(', ')}`);
console.log(`skipped ${skipped.length} (no data-chrome="on"): ${skipped.join(', ')}`);
if (CHECK && changed.length) { console.error('--check: pages are out of date'); process.exit(1); }
